sudo: required
services:
    - docker

before_install:
    - docker build -t atsangarides/docker-flask -f Dockerfile.dev .

script:
    - docker run atsangarides/docker-flask pytest

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-flask"
    env: "DockerFlask-env"
    bucket_name: "elasticbeanstalk-eu-west-2-983627010696"
    bucket_path: "docker-flask"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY